version: "3.8"

services:
  frontend:
    build:
      context: ./client
    ports:
      - "80:80"
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
